#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "dev" ]; then
  echo "❌ Commit interdit directement sur $branch"
  echo "Travaille sur une branche feature/fixture puis ouvre une PR."
  exit 1
fi
